### ISSUE TITLE
Shells that don't exist can be set

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/hashbangctl#15]
```
07:44:07 <bibek> oh really? oh why would it silently let me [change] it to that.
```

We should -probably- check if a shell exists before we set users up to fail in authentication.

**Comment by KellerFuchs** [comment]
@ChickenNuggers We “always” did.
Since #13 it is based on `/etc/shell`, unfortunately a bug was introduced and fixed in https://github.com/hashbang/hashbangctl/commit/8fe9ad8e171654277f9a7e7262b647a6d7a32280

For _some_ reason **cough**pip**cough**, the fixed version was installed properly everywhere except on `da1`.

**Comment by RyanSquared** [comment]
> For some reason coughpipcough, the fixed version was installed properly everywhere except on da1.

Huh. I thought I fixed that. Actually, I think da1 was the only one without the bug [I fixed]?

**Comment by KellerFuchs** [comment]
@ChickenNuggers Looks like there is a link missing.
In any case, running [`shell.yml`](https://github.com/hashbang/admin-tools/blob/master/shell.yml) ends with a pip failure.
